version: "2.4"
services:
  api:
    image: zx-ventures/api-partners
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - ENV=production
    command: >
        bash -c "/entrypoint/wait-for-it.sh db:3306
        && python manage.py migrate
        && python manage.py loaddata initial_data/partners.json
        && python manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY='secretkey'
      - DB_NAME=api_partners
      - DB_USER=root
      - DB_PASSWORD=dummypass
      - DB_HOST=db
      - DB_PORT=3306
      - DJANGO_DEBUG=False
    ports:
      - 8070:8000
    volumes:
      - "./src:/src"
    
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=dummypass
      - MYSQL_DATABASE=api_partners
    ports:
      - 3313:3306
    command:
    - --character-set-server=utf8
    - --collation-server=utf8_general_ci
    - --skip-character-set-client-handshake